#puerto local
server.port=8081

spring.application.name=instantcard

#validations
constraint-validator-payload=US

#conexion service bus
spring.jms.servicebus.connection-string=Endpoint=sb://${ConexionStringSB}
spring.jms.servicebus.idle-timeout=20000
spring.jms.servicebus.pricing-tier=basic
time-recive-message = 60

timeOutReceiverClient = 20

#Service VISION
service-id.vision=AZXAPSBF
service-id.vision-account-add=AZXAAS1
service-id.vision-customer-add=AZXNAS2
service-id.vision-sendername=orquestacion.to.visionplus.integracion.req.lq
service-id.vision-receivername=visionplus.to.orquestacion.integracion.rsp.lq

#Service VISION FISERV
service-url.fiserv.create-instant-card=${fiserv.url.base}/account/v2/instantCard
service-url.fiserv.login=${fiserv.url.base}/token
fiserv-login.grant-type=client_credentials
#fiserv-login.api-key=${Apikey-firstdata}
#fiserv-login.password=${Secret-firstdata}

#Service IBS
service-id.ibs=9000635
service-id.ibs-sendername=orquestacion.to.babroker.integracion.req.lq
service-id.ibs-receivername=babroker.to.orquestacion.integracion.rsp.lq

catalogo-logosemp = logosEmp
catalogo-producto-lms = ProductLMS
catalogo-cycle = CICLOS

# Embosser Update QA/Dev
mtls.port = 80
ingress-gateway-ip = http://${ingressGatewayIP}:${mtls.port}
embosser-update-url=${ingress-gateway-ip}/embosserUpdate?scope=${mtls.scope.gestionTarjeta}
customeroffer-update-url=${ingress-gateway-ip}/customerofferUpdate?scope=${mtls.scope.customeroffer}

#En local
#embosser-update-url=https://api-dev.bancoagricola.com/orquestador-tdc/gestion-tarjeta/embosserUpdate

#En produccion
#embosser-update-url=http://${GestionTarjetasIp_KubectlOutput}:8081/embosserUpdate

cmc-validacion-tarjeta=${ingress-gateway-ip}/api/v1/paycore-modules/con_validaciontarjeta?scope=${mtls.scope.noMonetaria}
cmc-creacion-cliente=${ingress-gateway-ip}/api/v1/paycore-modules/con-newCustomer?scope=${mtls.scope.noMonetaria}
cmc-bitacora-tarjeta=${ingress-gateway-ip}/api/v1/paycore-modules/save-daily-credit-card?scope=${mtls.scope.noMonetaria}
catalogo-validaciones-cmc=${ingress-gateway-ip}/api/v1/paycore-modules/catalogos?scope=${mtls.scope.noMonetaria}
instant-card-cmc=${ingress-gateway-ip}/api/v1/paycore-modules/insert-instant-card?scope=${mtls.scope.noMonetaria}


#Datos de conexion a azure keyvault
spring.cloud.azure.keyvault.secret.property-source-enabled=true
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint =${CMC_KEYVAULT_URI}
spring.cloud.azure.keyvault.secret.property-sources[0].credential.client-id=${CMC_CLIENT_ID}
spring.cloud.azure.keyvault.secret.property-sources[0].credential.client-secret=${CMC_SECRET_ID}
spring.cloud.azure.keyvault.secret.property-sources[0].profile.tenant-id=${TENANT_ID}
spring.cloud.azure.keyvault.secret.property-sources[0].client.connect-timeout=60
##Amount of time used when reading the server response.
spring.cloud.azure.keyvault.secret.property-sources[0].client.read-timeout=60
spring.cloud.azure.keyvault.secret.property-sources[0].refresh-interval=30m

mtls.scope.noMonetaria = api/v1/paycore-modules
mtls.scope.gestionTarjeta = orquestador-tdc/gestion-tarjeta
mtls.scope.customeroffer = api/disp-oferta

#Canal
instantcard.fountain.value=BANCA MOVIL OMNI